# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tic_tac_toe.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("tic_tac_toe.proto", :syntax => :proto3) do
    add_message "protocol_buffers.tic_tac_toe.Game" do
      optional :player, :enum, 1, "protocol_buffers.tic_tac_toe.Player"
      repeated :board, :enum, 2, "protocol_buffers.tic_tac_toe.Player"
      repeated :history, :message, 3, "protocol_buffers.tic_tac_toe.Move"
    end
    add_message "protocol_buffers.tic_tac_toe.Move" do
      optional :index, :int32, 1
    end
    add_enum "protocol_buffers.tic_tac_toe.Player" do
      value :EMPTY, 0
      value :X, 1
      value :O, 2
    end
  end
end

module ProtocolBuffers
  module TicTacToe
    Game = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.tic_tac_toe.Game").msgclass
    Move = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.tic_tac_toe.Move").msgclass
    Player = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.tic_tac_toe.Player").enummodule
  end
end
