# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: ultimate_tic_tac_toe.proto for package 'protocol_buffers.ultimate_tic_tac_toe'

require "grpc"
require "ultimate_tic_tac_toe_pb"

module ProtocolBuffers
  module UltimateTicTacToe
    module PlayerService
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = "protocol_buffers.ultimate_tic_tac_toe.PlayerService"

        rpc :Play, Game, Move
      end

      Stub = Service.rpc_stub_class
    end
  end
end
