# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ultimate_tic_tac_toe.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ultimate_tic_tac_toe.proto", :syntax => :proto3) do
    add_message "protocol_buffers.ultimate_tic_tac_toe.Board" do
      repeated :cells, :enum, 1, "protocol_buffers.ultimate_tic_tac_toe.Player"
    end
    add_message "protocol_buffers.ultimate_tic_tac_toe.Game" do
      optional :player, :enum, 1, "protocol_buffers.ultimate_tic_tac_toe.Player"
      repeated :board, :message, 2, "protocol_buffers.ultimate_tic_tac_toe.Board"
      optional :any_local_board, :bool, 3
      optional :local_board_index, :int32, 4
      repeated :history, :message, 5, "protocol_buffers.ultimate_tic_tac_toe.Move"
    end
    add_message "protocol_buffers.ultimate_tic_tac_toe.Move" do
      optional :global_index, :int32, 1
      optional :local_index, :int32, 2
    end
    add_enum "protocol_buffers.ultimate_tic_tac_toe.Player" do
      value :EMPTY, 0
      value :X, 1
      value :O, 2
    end
  end
end

module ProtocolBuffers
  module UltimateTicTacToe
    Board = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.ultimate_tic_tac_toe.Board").msgclass
    Game = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.ultimate_tic_tac_toe.Game").msgclass
    Move = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.ultimate_tic_tac_toe.Move").msgclass
    Player = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protocol_buffers.ultimate_tic_tac_toe.Player").enummodule
  end
end
