# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lib/ultimate_tic_tac_toe/protos/ultimate_tic_tac_toe.proto for package 'ultimate_tic_tac_toe.protos'

require "grpc"

module UltimateTicTacToe
  module Protos
    module PlayerService
      class Service
        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = "ultimate_tic_tac_toe.protos.PlayerService"

        rpc :Play, Game, Move
      end

      Stub = Service.rpc_stub_class
    end
  end
end
